name: Xcode

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer

jobs:
  xcode:
    name: Xcode
    runs-on: macos-latest
    env:
      SIMULATOR: iPhone 15
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Resolve package dependencies
      run: xcodebuild -resolvePackageDependencies
    - name: Build
      run: >
        xcodebuild
        build-for-testing
        -scheme "Nodes-Package"
        -destination "name=$SIMULATOR,OS=latest"
        -skipPackagePluginValidation
    - name: Test
      run: >
        xcodebuild
        test-without-building
        -scheme "Nodes-Package"
        -destination "name=$SIMULATOR,OS=latest"
